[tool.poetry]
name = "blango"
version = "0.1.0"
description = "condio test blog"
authors = ["tutysara"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
